---
- name: Ensure Apache is Installed and Running
  hosts: all
  become: yes

  vars:
    source_file: ./myWebsite/index.html
    dest_file: /var/www/html/index.html

  tasks:
    - name: Install Apache Web Server
      yum:
        name: httpd
        state: latest

  tasks: 
    - name: Check and Print Linux Version
      debug: 
        var: ansible_os_family 

    - name: Ensure Apache is Enabled and Running
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Deploy Website
      copy:
        src: "{{ source_file }}"
        dest: "{{ dest_file }}"
        mode: '0644'
      notify: Reload Apache

  handlers:
    - name: Reload Apache
      service:
        name: httpd
        state: reloaded # reloaded and not restarted like astahov wanted to not interrupt website

