---
- name: Install Default Apache WebServer
  hosts: all 
  become: yes

  tasks:
  - name: Install Apache Webserver
    yum:  name=httpd state=latest

  - name: Start Apache and Enable it on every Boot
    service: name=httpd state=reloaded enabled=yes # 
