---
# Our goal is to separate this playbook and leave only the most important stuff here
- name: Import/Include Demo
  hosts: all
  become: yes

  vars:
   mytext: "Privet from Sam"
  
  tasks: 
  
  - name: Ping Test
    ping:

  - name: Create Folder1
    file:
      path: /home/admin/folder1
      state: directory
      mode: 0755

  - name: Create Folder2
    file:
      path: /home/admin/folder2
      state: directory
      mode: 0755

  - name: Create File1
    copy:
      dest: /home/admin/file1.txt
      content: |
        Text Line1, in file1
        Text Line2, in file1
        Text Line3, {{ mytext }}

  - name: Create File2
    copy:
      dest: /home/secret/file2.txt
      content: |
        Text Line1, in file2
        Text Line2, in file2
        Text Line3, {{ mytext }}
